{
    'name': 'KG Ultracare Purchase',
    'version': '16.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'KG',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Anal Joy',
    'maintainer': 'KG',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'purchase', 'sale_management','purchase_stock','partner_credit_limit','purchase_requisition','mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/activity_data.xml',
        # 'report/paper_format.xml',
        'report/report.xml',
        'report/purchase_order.xml',
        'report/purchase_details_report.xml',
        'report/pending_purchase_order_report.xml',
        'report/purchase_analysis_report.xml',
        'report/purchase_bill_register_report.xml',
        'report/purchase_order_detailed_report.xml',
        'report/purchase_return_report.xml',
        'report/purchase_analysis_detailed_report.xml',
        'report/inherit_purchase_order_report.xml',


        'wizard/purchase_analysis_wizard.xml',
        'wizard/multiple_vendor.xml',
        'wizard/purchase_details_wizard.xml',
        'wizard/pending_purchase_order.xml',
        'wizard/purchase_bill_register.xml',
        'wizard/purchase_order_detailed.xml',
        'wizard/purchase_analysis_detailed.xml',
        'wizard/purchase_return_wizard.xml',

        'views/purchase_order.xml',
        'views/purchase_agreement.xml',
        'views/res_config.xml',
        'views/res_partner_view.xml',
        'views/rfq_report_template.xml',
    ],
    # 'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,

}
