{
    'name': 'KG Ultracare Inventory',
    'version': '16.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'KG',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Anal P Joy',
    'maintainer': 'KG',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'stock', 'sale_management', 'mrp', 'kg_material_requisition', 'sale', 'purchase', 'report_xlsx',
                'stock_account',
                'hr_expense', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_group_demo.xml',
        'data/product_category.xml',

        'report/report.xml',
        'report/in_out_ledger_report.xml',
        'report/opening_stock_report.xml',
        'report/stock_report.xml',
        'report/production_goods_report.xml',
        'report/slow_moving_item_report.xml',
        'report/stock_adjustment_register_report.xml',
        'report/stock_ledger_report.xml',
        'report/delivery_slip.xml',

        'wizard/in_out_ledger_wizard.xml',
        'wizard/opening_stock_wizard.xml',
        'wizard/stock_report_wizard.xml',
        'wizard/production_goods_wizard.xml',
        'wizard/slow_moving_items_wizard.xml',
        'wizard/stock_adjustment_register_wizard.xml',
        'wizard/stock_ledger_wizard.xml',

        'views/product_view.xml',
        'views/inventory_valuation.xml',
        'views/stationary_consumption.xml',
        'views/stock_move_line.xml',
        'views/stock_quant.xml',
        'views/kg_spare_type.xml',
        'views/brand.xml',
        'views/groups.xml',
        'views/sub_group.xml',
        'views/kg_product_conf.xml',
        'views/stock_location.xml',
        'views/product_category.xml',
        'views/stock_picking.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,

}
