{
    'name': 'KG Ultracare Accounting',
    'version': '16.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'KG',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Anal Joy',
    'maintainer': 'KG',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'account', 'account_accountant', 'sh_pdc', 'account_online_synchronization'],
    'data': [
        'security/ir.model.access.csv',

        'report/report.xml',
        'report/unpaid_invoice_report.xml',
        'report/purchase_bill_account_report.xml',
        'report/debtors_status_report.xml',
        'report/bank_book_report.xml',
        'report/creditors_status_report.xml',
        'report/account_ledger_report.xml',
        'report/account_receivable_ledger_report.xml',
        'report/consolidated_aging_analysis_receivables_report.xml',
        'report/balance_sheet_schedule_report.xml',
        'report/bank_payment_register_report.xml',
        'report/bank_status_report.xml',
        'report/cash_receipts_register_report.xml',
        'report/cash_book_report.xml',
        'report/consolidated_account_ledger_report.xml',
        'report/cash_payments_register_report.xml',
        'report/bank_reconciliation_report.xml',
        'report/pdc_checklist_report.xml',
        'report/pdc_issue_register_report.xml',
        'report/pdc_receipt_register_report.xml',
        'report/pdc_maturity_report.xml',
        'report/pdc_outstanding_report.xml',
        'report/ac_aging_analysis_report.xml',
        'report/opening_balance_report.xml',
        'report/expense_purchase_summary_report.xml',
        'report/debit_notes_register_report.xml',
        'report/detailed_expense_report.xml',
        'report/income_statement_report.xml',
        'report/job_costing_report.xml',
        'report/missing_bank_receipts_report.xml',
        'report/petty_cash_book_report.xml',

        'wizard/unpaid_invoice_wizard.xml',
        'wizard/purchase_bill_register_wizard.xml',
        'wizard/debtors_status_wizard.xml',
        'wizard/bank_book_wizard.xml',
        'wizard/creditors_status_wizard.xml',
        'wizard/account_ledger_wizard.xml',
        'wizard/account_receivable_ledger_wizard.xml',
        'wizard/consolidated_aging_analysis_receivables_wizard.xml',
        'wizard/balance_sheet_schedule_wizard.xml',
        'wizard/bank_payment_register_wizard.xml',
        'wizard/bank_status_wizard.xml',
        'wizard/cash_receipts_register_wizard.xml',
        'wizard/cash_book_wizard.xml',
        'wizard/consolidated_account_ledger_wizard.xml',
        'wizard/cash_payments_register_wizard.xml',
        'wizard/bank_reconciliation_wizard.xml',
        'wizard/pdc_checklist_wizard.xml',
        'wizard/pdc_issue_register_wizard.xml',
        'wizard/pdc_receipt_register_wizard.xml',
        'wizard/pdc_maturity_wizard.xml',
        'wizard/pdc_outstanding_wizard.xml',
        'wizard/ac_aging_analysis_wizard.xml',
        'wizard/opening_balance_wizard.xml',
        'wizard/expense_purchase_summary_wizard.xml',
        'wizard/debit_notes_register_wizard.xml',
        'wizard/detailed_expense_wizard.xml',
        'wizard/income_statement_wizard.xml',
        'wizard/job_costing_wizard.xml',
        'wizard/missing_bank_receipts_wizard.xml',
        'wizard/petty_cash_book_wizard.xml',

        'views/approval_type.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/account_online_link.xml',

    ],
    # 'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,

}
