# -*- coding: utf-8 -*-
{
    'name': 'Open HRMS Gratuity Settlement',
    'version': '16.0.1.0.0',
    'summary': """Employee Gratuity Settlement""",
    'live_test_url': """https://youtu.be/NITjRN6a6Jc""",
    'author': 'Cybrosys Techno solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'category': 'Generic Modules/Human Resources',
    "license": "AGPL-3",
    'website': "https://www.openhrms.com",
    'depends': ['base', 'hr', 'account','hr_payroll'],
    'data': [
        'data/sequence.xml',
        'views/res_config_settings.xml',
        'views/hr_gratuity_view.xml',
        'views/hr_gratuity_accounting_configuration.xml',
        'views/gratuity_configuration_view.xml',
        'views/hr_contract_views.xml',
        'views/hr_training_view.xml',
        'security/ir.model.access.csv',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
