{
    'name': 'KG Ultracare Manufacturing',
    'version': '16.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'KG',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Anal P Joy',
    'maintainer': 'KG',
    'website': 'www.klystronglobal.com',
    'depends': ['base', 'sale_management', 'sale', 'mrp', 'stock', 'hr', 'maintenance', 'purchase',
                'kg_ultracare_inventory', 'project', 'account_accountant', 'kg_material_requisition','kg_ultracare_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/mail_template.xml',
        'wizard/prod_plan_view.xml',
        'wizard/change_warehouse_view.xml',
        'wizard/abnormal_wastage.xml',
        'wizard/raw_po_wizard_view.xml',
        'wizard/dummy_product.xml',
        'views/stock_move.xml',
        'views/stock_bom.xml',
        'views/kg_sales_forecast.xml',
        'views/period.xml',
        'views/shift_master.xml',
        'views/kg_mat_req_view.xml',
        'views/production_planning.xml',
        'views/purchase_request_view.xml',
        'views/product_shift_reporting.xml',
        'views/raw_material.xml',
        'views/product_transfer_view.xml',
        'views/stock_picking.xml',
        'views/mrp_view.xml',
        'views/sale_order_line.xml',
        'views/stock_lot.xml',

    ],
    'installable': True,
    'application': False,
    'auto_install': False,

}
